Import('env')

env = env.Clone()

env['LIBS'] = ['OpenCL']
env['LIBPATH'] = ['/opt/AMDAPPSDK-3.0/lib/x86_64']

#['controller', 'model', 'view']
obj = SConscript(dirs = ['model'], exports = 'env')

env.Program('cart', ['main.cpp'] + obj)